---
-
  hosts: dev
  name: "Running MYSQL Database as Docker Container using Ansible."
  remote_user: root
  tasks:
    -
      docker_container:
        env:
          DB_HOST: "{{ my_host }}"
          DB_NAME: "{{ my_name }}"
          DB_PASSWORD: "{{ my_password }}"
          DB_USER: "{{ my_user }}"
        image: "65.1.218.108:8082/demolaravel"
        name: demolaravelcon
        ports:
          - "9000:9000"
        recreate: true
        restart: true
        volumes:
          - "{{ db_volume }}:/var/lib/mysql"
      name: "Launch mysql database container"
  vars_files:
    - vars/vault.yml
